### ISSUE TITLE
Can't run the project using vgg19 weights

### ISSUE THREAD

**Issue by chaoyueziji** [serihiro/inference_engine#6]
The wrong type is don't support "flatten" type, but I absolute follow your readme to compile the project， I also use the weight link in your readme.

**Comment by serihiro** [comment]
@chaoyueziji 
Sorry for my late response.

Thank you for your report.
As I wrote at README.md, I have tested VGG19 only with the onnx model from https://github.com/onnx/models/tree/master/vision/classification/vgg/vgg19. 

Meanings, maybe your trained model may not be able to use with my sample script https://github.com/serihiro/inference_engine/blob/master/example/imagenet_vgg19.cpp.

If you need more onnx operator supports, please give me more details.
At least, currently [flatten operator](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Flatten) is not supported in this project.

**Comment by serihiro** [comment]
I will update the README.md to be clear which VGG19 model can work at my sample script.

**Comment by chaoyueziji** [comment]
OK，I will test it as soon as possible according to your updated method

**Comment by serihiro** [comment]
@chaoyueziji 
> I will test it as soon as possible according to your updated method

To avoid misunderstanding, my commend does not guarantee the update of this library. After testing the models of https://github.com/onnx/models/tree/master/vision/classification/vgg/vgg19 this with several versions, and if I find some problems I will fix this library. If I do not find any problems to run the models, I **MAY NOT** fix this library.

By the way, this is a **JUST TOY PROJECT**, not expected to be used in production or research.

So if you want to use this library for your model inference, I strongly recommend using [menoh](https://github.com/pfnet-research/menoh) instead. This is an also ONNX inference engine and this is  more sophisticated and useful than mine. And so faster because menoh uses Intel MKL library.

**Comment by serihiro** [comment]
Or just use [onnx runtime](https://github.com/microsoft/onnxruntime).

**Comment by serihiro** [comment]
@chaoyueziji 
I tested my [ImageNet + VGG19 example script](https://github.com/serihiro/inference_engine/blob/master/example/imagenet_vgg19.cpp)  with several versions of [onnx/models/vgg/vgg19](https://github.com/onnx/models/tree/master/vision/classification/vgg/vgg19). And I updated the README.md with the supported versions. And I have no plan to support other than them for now.

As I told you earlier, **THIS IS A JUST TOY PROJECT**. So I strongly recommend to use other library such as [menoh](https://github.com/pfnet-research/menoh) and [onnx runtime](https://github.com/microsoft/onnxruntime) for production or research.

# Conclusion
- I confirmed my VGG19 example script works for [onnx/models/vgg/vgg19](https://github.com/onnx/models/tree/master/vision/classification/vgg/vgg19) with ImageNet images (224 x 224).
- I **DO NOT** have a plan to support other than them in VGG19 example script.
- I **strongly recommend** to use other library to implement inference script, such like [menoh](https://github.com/pfnet-research/menoh) and [onnx runtime](https://github.com/microsoft/onnxruntime) for production or research.


## Appendix

Test script I used.

```bash
#!/bin/bash

if [ $# -ne 2 ]; then
  echo 'Usage: sh ./test.sh {executable_path} {image_path}'
  exit 1
fi

ONNX_MODEL_BASE_PATH="/Users/kazuhiroserizawa/Documents/onnx-model/VGG19"
TEST_MODEL_VERSION=(1.1 1.1.2 1.2 1.3)
EXECUTABLE_PATH=${1}
IMAGE_PATH=${2}

for version in ${TEST_MODEL_VERSION[@]}; do
  test_target="${ONNX_MODEL_BASE_PATH}/${version}/model.onnx"
  echo "test target: ${test_target}"
  ${EXECUTABLE_PATH} -i ${IMAGE_PATH} -m ${test_target}
done
```

The result.

```
❯ bash test.sh \
/Users/kazuhiroserizawa/Documents/cp-work/inference_engine/build/example/imagenet_vgg19.o \
/Users/kazuhiroserizawa/Documents/dataset/imagenet/n02342885/771002455_25ed1c48c9.jpg

test target: /Users/kazuhiroserizawa/Documents/onnx-model/VGG19/1.1/model.onnx
inference result
333   :   0.0961615
937   :   0.0132377
673   :   0.0103981
338   :   0.00968101
332   :   0.00910154
331   :   0.00835893
330   :   0.00755793
552   :   0.00696596
281   :   0.0069197
359   :   0.0067969
test target: /Users/kazuhiroserizawa/Documents/onnx-model/VGG19/1.1.2/model.onnx
inference result
333   :   0.0961615
937   :   0.0132377
673   :   0.0103981
338   :   0.00968101
332   :   0.00910154
331   :   0.00835893
330   :   0.00755793
552   :   0.00696596
281   :   0.0069197
359   :   0.0067969
test target: /Users/kazuhiroserizawa/Documents/onnx-model/VGG19/1.2/model.onnx
inference result
333   :   0.0961615
937   :   0.0132377
673   :   0.0103981
338   :   0.00968101
332   :   0.00910154
331   :   0.00835893
330   :   0.00755793
552   :   0.00696596
281   :   0.0069197
359   :   0.0067969
test target: /Users/kazuhiroserizawa/Documents/onnx-model/VGG19/1.3/model.onnx
inference result
333   :   0.0961615
937   :   0.0132377
673   :   0.0103981
338   :   0.00968101
332   :   0.00910154
331   :   0.00835893
330   :   0.00755793
552   :   0.00696596
281   :   0.0069197
359   :   0.0067969
```
